stages:
  - build
  - container
  - db
  - deploy
  
maven-build:
  stage: build
  script: 
    - mvn clean
  tags:
    - maven
   
container:
  stage: container
  script: 
    - start.sh
  tags:
    - container

db:
  stage: db
  script: 
    - ./populatedb.sh 
  tags:
    - db
    
deploy:
  stage: deploy
  script: 
    - git push heroku master
  tags:
    - heroku
