stages:
  - build
  - analyze
  - deploy
  
maven-build:
  stage: build
  script: 
    - mvn clean
  tags:
    - maven
    
kiuwan-complete-delivery-analysis:
  stage: analyze
  script: 
    - agent -n %CI_PROJECT_NAME% -s %CI_PROJECT_DIR% -l "GitLab build %CI_JOB_ID%" -as completeDelivery --user %KIUWAN_USER% --pass %KIUWAN_PASSWD% -cr "Fix Board" -wr
  tags:
    - kiuwan
    
deploy-tomcat:
  stage: deploy
  script: 
    - ant deploy
  tags:
    - tomcat
