stages:
  - build
  - tests
  - container
  - db
  - deploy
  
maven-build:
  stage: build
  script: 
    - mvn clean install
  tags:
    - maven
   
tests:
  stage: tests
  script:
    - java -cp /home/sebas/junit4.10/junit-4.10.jar/:./WebContent/WEB-INF/lib/chess.ar org.junit.runner.JUnitCore com.senas.core.UtilChessTest
  tags:
    - junit

container:
  stage: container
  script: 
    - start.sh
  tags:
    - container

db:
  stage: db
  script: 
    - ./populatedb.sh 
  tags:
    - db
    
deploy:
  stage: deploy
  script: 
    - git push heroku master
  tags:
    - heroku
