stages:
  - build
  - test
  - analyze
  - promote
  - deploy
  
maven-build:
  stage: build
  script: 
    - mvn clean
  tags:
    - maven
    
test-sonar:
  stage: test
  script: 
    - mvn sonar:sonar -Dsonar.projectKey=sebastianrevuelta_Chess -Dsonar.organization=sebastianrevuelta-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=8fdf86930411847804b9d797dd1a4b7acdfd2ae5
  tags:
    - test
    
kiuwan-complete-delivery-analysis:
  stage: analyze
  script: 
    - agent -n %CI_PROJECT_NAME% -s %CI_PROJECT_DIR% -l "GitLab build" -as completeDelivery --user %KIUWAN_USER% --pass %KIUWAN_PASSWD% -cr "Fix Board" -wr
  tags:
    - kiuwan_delivery

kiuwan-promote-to-baseline:
  stage: promote
  script: 
    - agent --promote-to-baseline -n %CI_PROJECT_NAME% -l "GitLab build" -pbl "v3.%CI_JOB_ID%" --user %KIUWAN_USER% --pass %KIUWAN_PASSWD% -cr "Fix Board" 
  tags:
    - kiuwan_promote
    
deploy-tomcat:
  stage: deploy
  script: 
    - ant deploy
  tags:
    - tomcat
