db:
  image: mysql
  ports:
    - 8306:3306
  volumes:
    - db_data:/var/lib/mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: platas76
    MYSQL_DATABASE: chess
    MYSQL_USER: chess
    MYSQL_PASSWORD: checkMate$_@76
chess:
  image: chess-game
  ports: 
    - 8087:8080
  links:
    - db
