db:
  image: mysql
  container_name: mysql_db
  ports:
    - 3306:3306
  volumes:
    - db_data:/var/lib/mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: q1w2e3r4
    MYSQL_DATABASE: chess
    MYSQL_USER: chess
    MYSQL_PASSWORD: checkMate$_@76
chess:
  image: sebastianrevuelta/chess-game:2.3
  container_name: chess
  ports: 
    - 8087:8080
  links:
    - db
